#!/bin/sh -e

input() {
	printf "> "
	read -r sel
	export sel
}

check_usage() {
	[ -z "$1" ] \
		&& echo "Usage: shovel <deck file>" \
		&& exit 1

	[ -f "$1" ] || exists=0
	[ "$exists" ] \
		&& echo "$1: Not a file" \
		&& exit 1

	# I don't know if it's my computer but for some reason
	# the script dies without an echo from check_usage
	echo > /dev/null
}


main_menu() {
	clear
	echo "
Welcome to shovel, an example of an interactive tunnel wrapper.
Deck used: '$1'.
Press Ctrl+c to exit.

1) Start the review.
2) Add a card.
3) Modify a card.
4) Browse cards.
"

	input
	echo "$sel" | grep -q "^[1-4]$" || main_menu "$1"

	# This code won't be reached if main_menu was just executed

	case "$sel" in
		1) start_review "$1" ;;
		2) add_card "$1" ;;
		3) modify_card "$1" ;;
		4) browse_cards "$1" ;;
	esac
}

add_card() {
	clear
	echo "
Enter a front side for the card.
- Tabs cannot be used in cards, so they will be converted to spaces.
- Press Ctrl+c if you wish to exit.
"
	input
	front="$(echo "$sel" | sed "s/	/    /g")"

	clear
	echo "
Enter a back side for the card.
- Tabs cannot be used in cards, so they will be converted to spaces.
- Press Ctrl+c if you wish to exit.
"
	input
	back="$(echo "$sel" | sed "s/	/    /g")"

	while :
	do
		clear
		echo "
Your card's front, surrounded by pipes:
|$front|
Your card's back, surrounded by pipes:
|$back|

Press Ctrl+c to exit.

1) Confirm
2) Restart
"

		input
		echo "$sel" | grep "^[1-2]$" && break
	done

	case "$sel" in
		1)
			echo "$front	$back" >> "$1"

			clear
			echo "
Your card was successfully added to '$1'.
Press Enter to continue.
"

			read
			main_menu "$1" ;;

		2) add_card "$1" ;;
	esac
}

modify_card() {
	clear

	fzf --version > /dev/null 2>&1 || broken=1
	if [ "$broken" ]
	then
		echo "
You do not have fzf installed, which is used for selection.
Press Enter to go back to the main menu.
"
		read
		main_menu "$1"
	fi

	echo "Pick a card to modify."
	echo "Press Enter to continue."
	read

	exit
}

browse_cards() {
	clear

	${PAGER:-less} "$1"
	main_menu "$1"
}

start_review() {
	echo "Starting the review"

	exit
}

check_usage "$1"
main_menu "$1"
